server:
  port: 8081
spring:
  mvc:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
zero2dev:
  session_expired_after: 2
  max_session_exists: 1
  time_back_track: 1
  max_failed_login: 5
  access_token_expired_after: 30
  refresh_token_expired_after: 7
  unban_after_hour: 1
  username: "admin"
  timeout: 5000
